[core]
# enable debug mode
debug = true
heartbeat = 30

[master]
listen = "127.0.0.1:3652"

[gate]
listen = "127.0.0.1:3653"
client_listen = "127.0.0.1:13653"

[login]
listen = "127.0.0.1:3654"

[game]
listen = "127.0.0.1:3655"

[db]
listen = "127.0.0.1:3656"

# Redis server config
[redis]
host = "127.0.0.1"
port = 6357

# Mysql server config
[database]
host = "127.0.0.1"
port = 3306
name = "nano_server"
password = "root"
username = "root"
args = "charset=utf8mb4"
max_idle_conns = 20
max_open_conns = 15
show_sql = true

